[package]
name = "yas"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/lambdaclass/yet-another-swap/"
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.2.0"
cairo_finance = { git = "https://github.com/dpinones/cairo_finance", branch = "add-signed-integer" }

[[target.starknet-contract]]

