[package]
name = "fractal_swap"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = "2.0.1"
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "5bd0544" }

[[target.starknet-contract]]

[lib]
casm = true
