[package]
name = "fractal_swap"
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/lambdaclass/fractal_swap/"
# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.2.0"
orion = { git = "https://github.com/dpinones/orion" }

[[target.starknet-contract]]

