[package]
name = "fractal_swap"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[workspace]
members = [
    "crates/**",
]

[crate_roots]
tests = "tests"

[dependencies]
starknet = "2.0.1"
liquidity_math = { path = "crates/liquidity_math" }

[[target.starknet-contract]]

[lib]
casm = true
