[package]
name = "yas_faucet"
version = "0.1.0"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
yas_core = { path = "../yas_core" }

[[target.starknet-contract]]
sierra = true

[cairo]
sierra-replace-ids = true
